version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/microservices4vaadin
    steps:
      - checkout
      - restore_cache:
          key: microservices4vaadin-{{ checksum "build.gradle" }}
      - run: ./gradlew clean build coveralls
      - save_cache:
          paths:
            - "~/.gradle"
          key: microservices4vaadin-{{ checksum "build.gradle" }}
      - deploy:
          name: Push image to docker hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              ./start-dockerPush.sh
            fi  