version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.5.1
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:4.0.2-alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:3.4.10
    ports:
      - "27017:27017"

  mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_USER=root
    volumes:  # Mount relative path source folder on host to absolute path destination folder on docker container
      - './docker-db-dump/:/docker-entrypoint-initdb.d/'
    ports:
      - "3306:3306"
