server:
  port: 8081
  contextPath: /ui
  use-forward-headers: true
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: example
    key-password: example
  session:
    persistent: false

vaadin:
  servlet:
    production-mode: false

spring:
  redis:
    host: localhost
    port: 6379

security:
  sessions: NEVER
  basic:
    enabled: false
management:
  security:
    enabled: false

logging:
  level:
    microservices4vaadin: DEBUG
    org.springframework.security: INFO
    com.netflix.discovery: 'OFF'

---
# For deployment in Docker containers
spring:
  profiles: docker
  redis:
    host: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
