version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.5.1
    
  redis:
    image: redis:4.0.2-alpine
    ports:
      - "6379:6379"
      
  mongodb:
    image: mongo:3.4.10

  eventstore:
    image: klhauser/microservices4vaadin-eventstore
    ports:
      - "6666:6666"
    links:
      - rabbitmq
      - mongodb
